config/routes.rb
Casa::Application.routes.draw do
  resources :nota

end

app/models/notum.rb
class Notum < ActiveRecord::Base
  attr_accessible :asignatura, :catedratico, :nota, :observaciones
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/nota_controller.rb
class NotaController < ApplicationController
  # GET /nota
  # GET /nota.json
  def index
    @nota = Notum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nota }
    end
  end

  # GET /nota/1
  # GET /nota/1.json
  def show
    @notum = Notum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notum }
    end
  end

  # GET /nota/new
  # GET /nota/new.json
  def new
    @notum = Notum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notum }
    end
  end

  # GET /nota/1/edit
  def edit
    @notum = Notum.find(params[:id])
  end

  # POST /nota
  # POST /nota.json
  def create
    @notum = Notum.new(params[:notum])

    respond_to do |format|
      if @notum.save
        format.html { redirect_to @notum, notice: 'Notum was successfully created.' }
        format.json { render json: @notum, status: :created, location: @notum }
      else
        format.html { render action: "new" }
        format.json { render json: @notum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nota/1
  # PUT /nota/1.json
  def update
    @notum = Notum.find(params[:id])

    respond_to do |format|
      if @notum.update_attributes(params[:notum])
        format.html { redirect_to @notum, notice: 'Notum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nota/1
  # DELETE /nota/1.json
  def destroy
    @notum = Notum.find(params[:id])
    @notum.destroy

    respond_to do |format|
      format.html { redirect_to nota_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nota_helper.rb
module NotaHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Casa</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/nota/_form.html.erb
<%= form_for(@notum) do |f| %>
  <% if @notum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notum.errors.count, "error") %> prohibited this notum from being saved:</h2>

      <ul>
      <% @notum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<img width="350" src="index.png"/>
  <% end %>

  <div class="field">
    <%= f.label :asignatura %><br />
    <%= f.text_field :asignatura %>
  </div>
  <div class="field">
    <%= f.label :catedratico %><br />
    <%= f.text_field :catedratico %>
  </div>
  <div class="field">
    <%= f.label :nota %><br />
    <%= f.number_field :nota %>
  </div>
  <div class="field">
    <%= f.label :observaciones %><br />
    <%= f.text_area :observaciones %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nota/edit.html.erb
<h1>Editing notum</h1>

<%= render 'form' %>

<%= link_to 'Show', @notum %> |
<%= link_to 'Back', nota_path %>

app/views/nota/index.html.erb
<h1>Calificaciones Oscar Cerrato</h1>
<img src="index.png">
<table>
  <tr>
    <th>Asignatura </th>
<br>
    <th>Catedratico </th>
 <br>   <th>Nota </th>
  <br>  <th>Observaciones </th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nota.each do |notum| %>
  <tr>
    <td><%= notum.asignatura %></td>
    <td><%= notum.catedratico %></td>
    <td><%= notum.nota %></td>
    <td><%= notum.observaciones %></td>
    <td><%= link_to 'Mostrar', notum %></td>
    <td><%= link_to 'Editar', edit_notum_path(notum) %></td>
    <td><%= link_to 'Destruir', notum, method: :delete, data: { confirm: '¿Estas seguro?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo Ingreso', new_notum_path %>

app/views/nota/new.html.erb
<h1>Calificaciones Oscar Cerrato</h1>

<%= render 'form' %>

<%= link_to 'Back', nota_path %>

app/views/nota/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Asignatura:</b>
  <%= @notum.asignatura %>
</p>

<p>
  <b>Catedratico:</b>
  <%= @notum.catedratico %>
</p>

<p>
  <b>Nota:</b>
  <%= @notum.nota %>
</p>

<p>
  <b>Observaciones:</b>
  <%= @notum.observaciones %>
</p>


<%= link_to 'Edit', edit_notum_path(@notum) %> |
<%= link_to 'Back', nota_path %>